// Generated by https://quicktype.io

export interface LoginData {
    email:    string;
    password: string;
}

export interface LoginResponse {
    user:  User;
    token: string;
}

export interface User {
    _id:         string;
    username:    string;
    password:    string;
    email:       string;
    description: string;
    createdAt:   string;
    updatedAt:   string;
}
